replicaCount: 1

image:
  repository: crewmeister-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 45
    periodSeconds: 15
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10

env:
  SPRING_APPLICATION_NAME: crewmeister-challenge
  SPRING_DATASOURCE_USERNAME: crewmeister