replicaCount: 1

image:
  repository: crewmeister-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  name: http

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 90
    periodSeconds: 15
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 60
    periodSeconds: 10

monitoring:
  namespace: monitoring

env:
  SPRING_APPLICATION_NAME: crewmeister-challenge
  SPRING_DATASOURCE_USERNAME: crewmeister
  SPRING_PROFILES_ACTIVE: logstash
