apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "crewmeister.fullname" . }}-health-check
  namespace: {{ .Release.Namespace }}
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.service.port }}
        requestPath: {{ .Values.probes.liveness.path }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "crewmeister.fullname" . }}