apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crewmeister.fullname" . }}-db-secret
  labels:
    {{- include "crewmeister.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: "rootdev"
  mysql-password: "crewdev"
