elasticsearchHosts: "https://elasticsearch-master:9200"
elasticsearchCertificateSecret: "elasticsearch-master-certs"
elasticsearchCertificateAuthoritiesFile: "ca.crt"
elasticsearchCredentialSecret: "elasticsearch-master-credentials"

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 10
  successThreshold: 1
  timeoutSeconds: 5

resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

service:
  type: LoadBalancer